// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxubtwvcplkfifwoncgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dWJ0d3ZjcGxrZmlmd29uY2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxNjU2NjcsImV4cCI6MjA5Mzc0MTY2N30.9wZcpMktb0sq__wCcu3YeNliwJnXzV7zasdNKF-C1hU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Shared single-flight refresh to avoid concurrent token refresh races
// across tabs / hooks during PWA resumption and auth flows.
let _refreshPromise: Promise<void> | null = null;
let _lastRefreshAt = 0;
const REFRESH_THROTTLE_MS = 8000;

export async function ensureFreshSession(): Promise<void> {
  const now = Date.now();
  if (_refreshPromise) return _refreshPromise;
  if (now - _lastRefreshAt < REFRESH_THROTTLE_MS) return;

  _refreshPromise = (async () => {
    try {
      await supabase.auth.refreshSession();
      _lastRefreshAt = Date.now();
    } catch (err) {
      console.warn('ensureFreshSession: refresh failed', err);
    } finally {
      _refreshPromise = null;
    }
  })();

  return _refreshPromise;
}
