// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxubtwvcplkfifwoncgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dWJ0d3ZjcGxrZmlmd29uY2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxNjU2NjcsImV4cCI6MjA5Mzc0MTY2N30.9wZcpMktb0sq__wCcu3YeNliwJnXzV7zasdNKF-C1hU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});